name: Kith & Kin
favicon: null
layout_spectrum: 0.09192536538466811
typography_spectrum: 0.47631520917639136
title: Ecstasy in Distopia
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.7702016439288855
  lightness: 0.6094530634582043
  saturation: 0.618724119849503
  rhythmicContrast: 0.5698887153994292
purpose: []
